#!/bin/sh
read -p "Фамилия:  " FAM
read -p "Имя:      " NAME
read -p "Отчество: " SURNAME
read -p "Группа:   " GROUP
read -p "Время перебора 1-символьного пароля (мс):              " ANS1
read -p "Время перебора 2-символьного пароля (мс):              " ANS2
read -p "Время перебора 3-символьного пароля (мс):              " ANS3
read -p "Время перебора 4-символьного пароля (мс):              " ANS4
read -p "Оценочная скорость перебора (символов/мс):             " ANS5
read -p "Оценочное время перебора 8-символьного пароля (часов): " ANS6
FILE=lab1-report.$(date +%Y.%m.%d-%H:%M:%S).txt
echo "$FAM:$NAME:$SURNAME:$GROUP:$ANS1:$ANS2:$ANS3:$ANS4:$ANS5:$ANS6:`date +%s`" | reprep | base64 > $FILE
echo " *** Ваш отчет по лабораторной находится в файле $FILE. *** "
echo " *** Его необходимо загрузить в Moodle. *** "
